name: Create Archive
on:
  push:
     tags:
       - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      mission1: test.miz
      mission2: Cauasus Conflict.miz
    steps:
      - name: Checkout main
        uses: actions/checkout@main
      #### test.miz ####
      - name: Create zip
        uses: thedoctor0/zip-release@0.7.0
        with:
          type: "zip"
          filename: "${{ env.mission1 }}"
          directory: "tests/${{ env.mission1 }}"
      - name: Add to release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "tests/${{ env.mission1 }}/${{ env.mission1 }}"
          removeArtifacts: "true"
          allowUpdates: "true"
      #### Caucasus Conflict.miz ####
      - name: Create zip mission 2
        uses: thedoctor0/zip-release@0.7.0
        with:
          type: "zip"
          filename: "${{ env.mission2 }}"
          directory: "tests/${{ env.mission2 }}"
      - name: Add to release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "tests/${{ env.mission2 }}/${{ env.mission2 }}"
          removeArtifacts: "true"
          allowUpdates: "true"

